local ts = game:GetService("TweenService")
script.Parent.MouseEnter:Connect(function()
	local tw = ts:Create(script.Parent.Frame.Frame,TweenInfo.new(0.15),{ImageColor3=Color3.fromRGB(167, 205, 255)})
	tw:Play()
end)
script.Parent.MouseLeave:Connect(function()
	local tw = ts:Create(script.Parent.Frame.Frame,TweenInfo.new(0.15),{ImageColor3=Color3.fromRGB(255, 255, 255)})
	tw:Play()
end)